version: "3"

services:
  mongo:
    image: mongo:7
    container_name: mongo7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crmDB
    volumes:
      - mongo-data:/data/db
      - ./data:/data/import

  oracle:
    image: gvenzl/oracle-xe:21
    container_name: oracle-xe
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oraclepass
      ORACLE_DATABASE: XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  mongo-data:
  oracle-data: